[package]
name = "wc3-controller"
version = "0.1.0"
edition = "2024"
rust-version = "1.96.1"
publish = false

[dependencies]
sdl3 = { version = "=0.20.0", features = ["build-from-source-static", "build-from-source-unix-console"] }
enigo = "=0.6.1"
ctrlc = "3.5"

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = "0.14"
serde_json = "1.0"
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
